 const ADD_TODO = "ADD_TODO";
 const TOGGLE_TODO = "TOGGLE_TODO";
 const SET_FILTER = "SET_FILTER";
 const DELETE_TODO = "SET_FILTER";
 const FILTER_ALL = "ALL";
 const FILTER_COMPLETED="COMPLETED";
 const FILTER_INCOMPLETE="INCOMPLETED";
 const Filters = [FILTER_ALL, FILTER_COMPLETED, FILTER_INCOMPLETE];
export{ ADD_TODO,TOGGLE_TODO,SET_FILTER,DELETE_TODO,FILTER_ALL,FILTER_COMPLETED,FILTER_INCOMPLETE,Filters};